### ISSUE TITLE
Container is running as root

### ISSUE THREAD

**Issue by longstone** [RafaMunoz/bot-StorjNodeMonitor#2]
As a user, I want to specify user and group (`--user`) so that the container is not running as a root.

```
/opt/bot # id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
```

See https://docs.docker.com/engine/reference/run/#user

**Comment by RafaMunoz** [comment]
Now the container not run with user root and the user is storjnodemonitor.
You cand dowload the last image to tried.

**Comment by longstone** [comment]
Much better now, thanks!

```
/opt/bot $ id
uid=1000(storjnodemonitor) gid=1000(storjnodemonitor) groups=1000(storjnodemonitor)
```
